### ISSUE TITLE
Impossible to install `auto-sklearn` using conda due to strange requirement `__linux`

### ISSUE THREAD

**Issue by PertuyF** [conda-forge/auto-sklearn-feedstock#9]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

It is currently impossible to install `auto-sklearn` using conda due to the strange dependency `__linux`. Trying this will fail even when creating and environment.

Using conda:
```bash
conda create -n test auto-sklearn=0.14 -c conda-forge

...

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__unix==0=0
  - auto-sklearn=0.14 -> __linux
  - auto-sklearn=0.14 -> pynisher[version='>=0.6.3'] -> __unix

Your installed version is: not available
```

Or using mamba:
```bash
mamba create -n test auto-sklearn=0.14 -c conda-forge

...

Encountered problems while solving:
  - nothing provides __linux needed by auto-sklearn-0.14.0-pyhd8ed1ab_0
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by BastianZim** [comment]
auto-sklearn is only available on Linux (Which is where this restriction is from), which OS are you on?

**Comment by PertuyF** [comment]
This is happening under Linux Ubuntu.
I am surprised to find this kind of requirement standing for a Linux restriction. I thought this is usually done using `skip` + selectors.

My understanding is that "__linux" is not an actual package and that conda/mamba is not able to satisfy this dependency.

**Comment by BastianZim** [comment]
`__linux` was introduced some time ago along the other virtual packages and is used on `noarch` to restrict the os. `Skips` is only used in arch specific packages. 

If this breaks in your environment, I would suggest updating to the newest version of conda/mamba or, otherwise, filing an issue in conda, as this is working on our CIs so it sounds like a bug in your system. 

Ref https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html

**Comment by BastianZim** [comment]
@PertuyF Can you confirm if this issue still exists?

**Comment by PertuyF** [comment]
@BastianZim I have one Cloud VM on which the issue persists, updating conda and mamba won't change that.
I was able to install correctly on other similar systems though, so it is likely due to this VM specifically. Thank you for your support and let's close this issue.

**Comment by BastianZim** [comment]
One last comment: If you run `conda info` you should be able to see all virtual packages currently available.

**Comment by PertuyF** [comment]
Great, I did not know this!
It makes sense, the machine where it fails does not have the `__linux` virtual package. As it is a Cloud VM running a vendor provided image, there may have been tweaks that broke the way conda detects the system.
I'll investigate, but it is definitely not related to `auto-sklearn`.
